import Head from 'next/head'
import Image from 'next/image'
import About from '../components/About'
import Navbar from '../components/Navbar'

export default function Home () {
  return (
    <div>
      <Head>
        <title>Lucas Lomeu - Frontend Developer</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      {/* Navbar */}
      <Navbar />

      <div className='w-full h-screen text-justify mt-28'>
        <div className='max-w-[768px] w-full mx-auto p-2 flex justify-center items-left flex-col gap-y-12 divide-y divide-neutral-800'>
          {/* About */}
          <div className='flex flex-col gap-y-4'>
            <p className='text-2xl text-neutral-200 font-bold tracking-wide'>
              Olá, sou <span className='text-indigo-400'>Lucas Lomeu.</span>
            </p>
            <p className='text'>
              Desenvolvedor frontend, bacharel em Engenharia Civil. Atualmente
              atuando como desenvoledor frontend na Proft, sendo responsável por
              todos os projetos relacionados a frontend na empresa, utilizando
              ReactJS, ReactNative e Electron.
            </p>
            <p className='text'>
              Atualmente aprimorando meus conhecimentos em ReactJS para
              proporcionar belas aplicações que possam fazer com que o usuário
              tenha excelentes experiências web.
            </p>
            <div className='flex gap-x-5'>
              <div className='btn-social'>Github</div>
              <div className='btn-social'>LinkedIn</div>
              <div className='btn-social'>Email</div>
            </div>
          </div>
          {/* Skills */}
          <div className='container'>
            <h1>Experiência</h1>
            <div className='content-skill'>
              <div className='header-container'>
                <h2>Desenvolvedor Frontend</h2>
                <h3>18/02 - Atualmente</h3>
              </div>
              <h3>Proft</h3>
              <p className='text'>
                Desenvolvimento de novas features e manutenção de código,
                principalmente com ReactJS, porém também atuando com Electron e
                React Native. Utilização de Styled Components ou MaterialUI para
                estilização e git para versionamento de código.
              </p>
            </div>
            <div className='content-skill'>
              <div className='header-container'>
                <h2>Estagiário de Engenharia Civil</h2>
                <h3>02/20 - 08/20</h3>
              </div>
              <h3>Rede HG</h3>
              <p className='text'>
                Estagiário de Engenharia Civil na construção do posto de
                gasolina “Posto Ferrari” da Rede HG. Tendo como principais
                atividades: orçamento e compra de materiais; relatório de obra;
                gestão de equipe; acompanhamento da execução da obra.
              </p>
            </div>
            <div className='content-skill'>
              <div className='header-container'>
                <h2>Professor particular</h2>
                <h3>07/19 - 12/19</h3>
              </div>
              <h3>Autônomo</h3>
              <p className='text'>
                Professor particular para alunos do ensino fundamental e ensino
                médio, com foco nos conteúdos de matemática; física e química.
                Sendo as aulas de acordo com o que o aluno está aprendendo na
                escola, reforçando o que está sendo ensinado, tirando dúvidas e
                realizando exercícios para fixação.
              </p>
            </div>
            <div className='content-skill'>
              <div className='header-container'>
                <h2>Assistente Administrativo</h2>
                <h3>07/17 - 02/19</h3>
              </div>
              <h3>Secretaria Municipal de Cultura, Esporte e Lazer</h3>
              <p className='text'>
                Vistoria e inspeção dos Pontos de Cultura de Governador
                Valadares, auxiliando na Prestação de Contas e outras demandas;
                orçamentos; criação de oficios e termos de licitação.
              </p>
            </div>
          </div>
          {/* Projetos */}
          <div className='container'>
            <h1>Projetos</h1>
            <div className='content-skill'>
              <div className='header-container'>
                <h2>LomeuShop</h2>
                <div className='flex flex-row gap-x-2'>
                  <div className='btn-project'>source</div>
                  <div className='btn-project'>demo</div>
                </div>
              </div>
              <div className='project-lang'>
                <h3>ReactJS</h3>
                <h3>SASS</h3>
              </div>
              <div className='text'>
                Website desenvolvido durante um teste para uma empresa, tenho
                como objetivo um simples carrinho de compras.
              </div>
            </div>

            <div className='content-skill'>
              <div className='header-container'>
                <h2>CryptoCurrency</h2>
                <div className='flex flex-row gap-x-2'>
                  <div className='btn-project'>source</div>
                  <div className='btn-project'>demo</div>
                </div>
              </div>
              <div className='project-lang'>
                <h3>ReactJS</h3>
                <h3>API</h3>
                <h3>Styled Components</h3>
              </div>
              <div className='text'>
                Realizado para estudo de consumo de API, utilizando ReactJS e
                StyledComponents. O projeto foi desenvolvido para aplicação de
                criptomoedas, como o Bitcoin, Ethereum, Litecoin, etc.
              </div>
            </div>

            <div className='content-skill'>
              <div className='header-container'>
                <h2>MovieSearch</h2>
                <div className='flex flex-row gap-x-2'>
                  <div className='btn-project'>source</div>
                  <div className='btn-project'>demo</div>
                </div>
              </div>
              <div className='project-lang'>
                <h3>ReactJS</h3>
                <h3>API</h3>
                <h3>SASS</h3>
              </div>
              <div className='text'>
                Foi desenvolvido um site de busca de filmes utilizando a api
                YTS, onde é possível obter informações e até mesmo realizar o
                download via torrent.
              </div>
            </div>

            <div className='content-skill'>
              <div className='header-container'>
                <h2>Álbum de Fotos</h2>
                <div className='flex flex-row gap-x-2'>
                  <div className='btn-project'>source</div>
                  <div className='btn-project'>demo</div>
                </div>
              </div>
              <div className='project-lang'>
                <h3>ReactJS</h3>
                <h3>API</h3>
                <h3>SASS</h3>
              </div>
              <div className='text'>
                Website desenvolvido para busca de fotos, utilizando a API da
                Pexel, sendo possível realizar o download da foto escolhida em
                tamanhos variados.
              </div>
            </div>

            <div className='content-skill'>
              <div className='header-container'>
                <h2>Corona Stats</h2>
                <div className='flex flex-row gap-x-2'>
                  <div className='btn-project'>source</div>
                  <div className='btn-project'>demo</div>
                </div>
              </div>
              <div className='project-lang'>
                <h3>ReactJS</h3>
                <h3>API</h3>
                <h3>SASS</h3>
              </div>
              <div className='text'>
                Estudo de consumo de API, consumindo dados de covid-19 nos
                estados Brasileiros.
              </div>
            </div>
          </div>
          {/* Blog */}
          <div className='container'></div>
          {/* Contato  */}
          <div className='container'></div>
        </div>
      </div>
    </div>
  )
}
